# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    allowBrokenSymlinks: 
    
  - task: CopyFiles@2

  displayName: 'Copy Build Artifact to Staging Directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '*.jar' # Use '*.war' if building a WAR file
    TargetFolder: '$(buildDir)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact to Azure DevOps'
  inputs:
    PathtoPublish: '$(buildDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


