pipeline {
  agent any

 // tools {
 //   terraform 'Terraform_1.7'
 // }

  environment {
    BACKEND_DIR = "eks/backend"
    MAIN_DIR = "eks"
  }

  stages {
    stage('Checkout') {
      steps {
       git branch: 'master', url: 'https://github.com/coach4u/java-jenkins-example.git'
       sh 'echo "Listing files under eks/backend:" && ls -la eks/backend'
      }
    }

    stage('Create Backend') {
      steps {
          dir("${BACKEND_DIR}") {
          sh '''
            pwd
            ls -l
            terraform init
            terraform apply -auto-approve
          '''
        }
       }
     }
    
  
    stage('Init Infra with Remote Backend') {
      steps {
        dir("${MAIN_DIR}") {
          sh '''
            terraform init
            terraform plan
          '''
        }
      }
    }

    stage('Apply Infrastructure') {
      steps {
        dir("${MAIN_DIR}") {
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
