name: github actions
on: push 
jobs:
 building:
   runs-on: ubuntu-latest
   steps:
   - name: code checkout
     uses: actions/checkout@v4

   - name: Setup Java 11
     uses: actions/setup-java@v3
     with:
        distribution: 'temurin'
        java-version: '11'
   - name: Build and Run Tests
     run: mvn clean test checkstyle:checkstyle
     continue-on-error: true # Ensures reports are collected even if there are test failures

   - name: List target directory contents
     run: ls -al target

   - name: Archive Test and Checkstyle Reports
     if: always()  # This step will always run, even if previous steps fail
     uses: actions/upload-artifact@v3
     with:
        name: reports
        path: |
          target/surefire-reports
          target/checkstyle-result.xml
   
   - name: Build with Maven
     run: mvn clean package -DskipTests
