name: github actions
on: push 
jobs:
 building:
   runs-on: ubuntu-latest
   steps:
   - name: code checkout
     uses: actions/checkout@v4

   - name: Setup Java 11
     uses: actions/setup-java@v3
     with:
        distribution: 'temurin'
        java-version: '11'
   - name: testing the code
     run: mvn checkstyle:checkstyle
   - name: Archive Test and Checkstyle Reports
     if: always()  # Ensure this step runs even if the build fails
     uses: actions/upload-artifact@v3
      with:
        name: reports
        path: |
          target/surefire-reports
          target/checkstyle-result.xml
   
   - name: Build with Maven
     run: mvn clean package -DskipTests
